import type { Product, Review, FAQ } from './types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'bullpadel-vertex-04',
    name: 'Vertex 04 Pro',
    brand: 'Bullpadel',
    category: 'rackets',
    price: 289,
    salePrice: 229,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    description: 'The Vertex 04 Pro is engineered for aggressive offensive players who demand power and control in every shot.',
    longDescription: 'Built with a revolutionary carbon fiber frame and a premium EVA Soft foam core, the Vertex 04 Pro delivers explosive power while maintaining outstanding control. The diamond shape maximizes the sweet spot for advanced players seeking to dominate from the back of the court.',
    features: [
      'High Modulus Carbon fiber frame',
      'EVA Soft foam core for superior control',
      'Diamond shape for maximum power',
      'Anti-vibration system',
      'Premium grip included',
    ],
    playerLevel: 'advanced',
    weight: '355–375g',
    balance: 'High balance (offensive)',
    shape: 'Diamond',
    material: 'Carbon fiber + fiberglass',
    image: { gradient: 'from-[#0a0a0a] via-[#151515] to-[#0d0d0d]', accent: '#b5f72e' },
    rating: 4.9,
    reviewCount: 142,
    inStock: true,
    stockCount: 8,
  },
  {
    id: '2',
    slug: 'nox-ml10-pro-cup',
    name: 'ML10 Pro Cup Black',
    brand: 'Nox',
    category: 'rackets',
    price: 319,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    description: 'Miguel Lamperti signature racket. Maximum control meets extreme precision for elite-level play.',
    longDescription: 'Co-designed with professional player Miguel Lamperti, the ML10 Pro Cup Black is the choice of champions. Its unique round shape and multilayer carbon construction deliver the perfect blend of control and precision that professionals demand.',
    features: [
      '100% Carbon fiber construction',
      'SMART CROWN technology',
      'Round shape for superior control',
      'Double Carbon fibre layers',
      'Aluminun Power System',
    ],
    playerLevel: 'professional',
    weight: '360–380g',
    balance: 'Low-medium balance (control)',
    shape: 'Round',
    material: '100% Carbon fiber',
    image: { gradient: 'from-[#080808] via-[#0f1a0a] to-[#050505]', accent: '#b5f72e' },
    rating: 4.8,
    reviewCount: 98,
    inStock: true,
    stockCount: 5,
  },
  {
    id: '3',
    slug: 'head-alpha-pro',
    name: 'Alpha Pro 2025',
    brand: 'Head',
    category: 'rackets',
    price: 199,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    description: 'The perfect racket for intermediate players ready to take their game to the next level.',
    longDescription: 'The Head Alpha Pro 2025 bridges the gap between beginner and advanced play. Its teardrop shape provides a generous sweet spot while the fiberglass and carbon construction offers excellent power-to-weight ratio.',
    features: [
      'Carbon fiber + fiberglass construction',
      'Teardrop shape for versatility',
      'Medium balance for all-round play',
      'Comfort Foam core',
      'Protective edge guard',
    ],
    playerLevel: 'intermediate',
    weight: '360–375g',
    balance: 'Medium balance (all-round)',
    shape: 'Teardrop',
    material: 'Carbon fiber + fiberglass',
    image: { gradient: 'from-[#0a0a12] via-[#0f0f1a] to-[#080810]', accent: '#6366f1' },
    rating: 4.7,
    reviewCount: 203,
    inStock: true,
    stockCount: 15,
  },
  {
    id: '4',
    slug: 'adidas-metalbone-ht',
    name: 'Metalbone HT 3.3',
    brand: 'Adidas',
    category: 'rackets',
    price: 379,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    description: 'The pinnacle of Adidas padel engineering. Extreme power, extreme control, zero compromise.',
    longDescription: 'The Adidas Metalbone HT 3.3 is the weapon of choice for professional players seeking maximum performance. Its DUAL EXOSKELETON technology creates an extremely rigid frame that transfers maximum energy into every shot.',
    features: [
      'DUAL EXOSKELETON technology',
      'METALBONE frame construction',
      'SPINTECH surface texture',
      'EVA-HYBRIDFOAM core',
      'Extreme diamond shape',
    ],
    playerLevel: 'professional',
    weight: '365–380g',
    balance: 'Very high balance (power)',
    shape: 'Diamond',
    material: 'Carbon fiber + aluminum alloy',
    image: { gradient: 'from-[#0a0808] via-[#151010] to-[#080808]', accent: '#ef4444' },
    rating: 4.9,
    reviewCount: 76,
    inStock: true,
    stockCount: 3,
  },
  {
    id: '5',
    slug: 'head-padel-balls-pro',
    name: 'Pro Padel Balls (4-Tube)',
    brand: 'Head',
    category: 'balls',
    price: 12.99,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    description: 'ITF and FIP approved padel balls for professional tournament play. Exceptional durability and consistent bounce.',
    longDescription: 'Head Pro padel balls are used at the highest level of competition worldwide. Each ball is precision-engineered for consistent pressure, optimal bounce height, and extended durability on any court surface.',
    features: [
      'FIP & ITF approved',
      'Consistent internal pressure',
      'Premium felt for durability',
      'Optimal bounce height',
      'Pack of 4 balls',
    ],
    image: { gradient: 'from-[#0a0a08] via-[#141408] to-[#0d0d07]', accent: '#eab308' },
    rating: 4.8,
    reviewCount: 512,
    inStock: true,
  },
  {
    id: '6',
    slug: 'bullpadel-balls-official',
    name: 'Official Match Balls (3-Tube)',
    brand: 'Bullpadel',
    category: 'balls',
    price: 9.99,
    salePrice: 7.99,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    description: 'Professional match-grade balls with superior pressure retention for competitive play.',
    longDescription: 'Bullpadel Official balls are designed for match play with superior pressure retention and consistent bounce. The premium felt construction provides excellent spin response and durability.',
    features: [
      'High pressure retention',
      'Premium quality felt',
      'Excellent spin response',
      'Pack of 3 balls',
      'All court surfaces',
    ],
    image: { gradient: 'from-[#0a0c08] via-[#12160a] to-[#0a0c08]', accent: '#84cc16' },
    rating: 4.6,
    reviewCount: 287,
    inStock: true,
  },
  {
    id: '7',
    slug: 'head-xtreme-soft-grip',
    name: 'Xtreme Soft Grip (3-Pack)',
    brand: 'Head',
    category: 'grips',
    price: 14.99,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    description: 'Ultra-soft overgrip for maximum comfort and moisture absorption during intense matches.',
    longDescription: 'The Head Xtreme Soft Grip provides exceptional comfort with its ultra-thin construction and advanced moisture absorption technology. Perfect for players who sweat heavily or prefer a softer feel in their hands.',
    features: [
      'Ultra-soft texture',
      'Superior moisture absorption',
      'Thin 0.6mm profile',
      'Anti-slip surface',
      'Pack of 3 grips',
    ],
    color: 'White / Black / Lime',
    image: { gradient: 'from-[#080a0a] via-[#0f1212] to-[#080a0a]', accent: '#22d3ee' },
    rating: 4.7,
    reviewCount: 435,
    inStock: true,
  },
  {
    id: '8',
    slug: 'bullpadel-tour-bag',
    name: 'Tour Pro Bag 2025',
    brand: 'Bullpadel',
    category: 'bags',
    price: 129,
    salePrice: 99,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    description: 'Professional padel tour bag with thermal pocket for up to 3 rackets and full gear organization.',
    longDescription: 'The Bullpadel Tour Pro Bag is the complete solution for serious players. With a dedicated thermal pocket protecting up to 3 rackets from extreme temperatures, multiple compartments for shoes, clothing, and accessories, and ergonomic shoulder straps, this bag is built for the demanding touring professional.',
    features: [
      'Thermal pocket for 3 rackets',
      'Separated shoe compartment',
      'Multiple accessory pockets',
      'Water-resistant material',
      'Ergonomic padded straps',
    ],
    color: 'Black / Lime',
    image: { gradient: 'from-[#0a0a0a] via-[#121512] to-[#080a08]', accent: '#b5f72e' },
    rating: 4.8,
    reviewCount: 167,
    inStock: true,
    stockCount: 12,
  },
  {
    id: '9',
    slug: 'adidas-adipower-ctrl-3',
    name: 'Adipower CTRL 3 Shoes',
    brand: 'Adidas',
    category: 'shoes',
    price: 149,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    description: 'Elite padel shoes engineered for explosive lateral movement and all-court grip performance.',
    longDescription: 'The Adidas Adipower CTRL 3 combines advanced court grip technology with superior lateral support for the demands of modern padel. The herringbone outsole pattern delivers optimal traction on all court surfaces while the cushioned midsole protects against impact.',
    features: [
      'Herringbone grip outsole',
      'BOOST cushioning technology',
      'Reinforced toe cap',
      'Breathable mesh upper',
      'Lateral support system',
    ],
    size: 'EU 38–48',
    color: 'Black / White / Lime',
    image: { gradient: 'from-[#080810] via-[#0f0f1a] to-[#080810]', accent: '#818cf8' },
    rating: 4.7,
    reviewCount: 93,
    inStock: true,
  },
  {
    id: '10',
    slug: 'nox-shoes-nerbo-10',
    name: 'Nerbo 10 Performance',
    brand: 'Nox',
    category: 'shoes',
    price: 119,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    description: 'Lightweight performance shoes with exceptional grip for fast-paced padel movements.',
    longDescription: 'Nox Nerbo 10 shoes are designed for players who prioritize speed and agility. The lightweight construction and directional tread pattern provide excellent court feel and quick multidirectional movement.',
    features: [
      'Lightweight construction (< 400g)',
      'Directional tread pattern',
      'Padded ankle collar',
      'Quick-dry mesh upper',
      'Durable TPU reinforcements',
    ],
    size: 'EU 38–47',
    color: 'Black / Lime Green',
    image: { gradient: 'from-[#080a08] via-[#0f1a0f] to-[#080a08]', accent: '#b5f72e' },
    rating: 4.6,
    reviewCount: 124,
    inStock: true,
  },
  {
    id: '11',
    slug: 'nexor-performance-tee',
    name: 'NEXOR Performance Tee',
    brand: 'NEXOR',
    category: 'apparel',
    price: 49.99,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    description: 'Premium padel performance tee with DryFit technology and bold NEXOR branding.',
    longDescription: 'The NEXOR Performance Tee is engineered for high-intensity padel sessions. The advanced moisture-wicking fabric keeps you cool and dry throughout your match, while the athletic cut allows full freedom of movement.',
    features: [
      'DryFit moisture-wicking technology',
      'Athletic cut for full mobility',
      'Anti-odor treatment',
      'UPF 30+ sun protection',
      'NEXOR brand detail',
    ],
    size: 'XS–XXL',
    color: 'Black with Lime accents',
    image: { gradient: 'from-[#050505] via-[#0f120a] to-[#050505]', accent: '#b5f72e' },
    rating: 4.8,
    reviewCount: 56,
    inStock: true,
  },
  {
    id: '12',
    slug: 'wilson-padel-wristband',
    name: 'Pro Wristband Set',
    brand: 'Wilson',
    category: 'accessories',
    price: 12.99,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    description: 'Premium cotton wristbands for superior sweat absorption during intense padel matches.',
    longDescription: 'Wilson Pro Wristbands are made from high-quality cotton-terry blend fabric for maximum sweat absorption. The elasticated design ensures they stay in place during the most intense rallies.',
    features: [
      'Cotton-terry blend',
      'High sweat absorption',
      'Elasticated wrist fit',
      'Machine washable',
      'Pack of 2 wristbands',
    ],
    color: 'White / Black / Lime',
    image: { gradient: 'from-[#0a0808] via-[#141010] to-[#0a0808]', accent: '#f87171' },
    rating: 4.5,
    reviewCount: 312,
    inStock: true,
  },
]

export const featuredProducts = products.filter(p => p.isFeatured)
export const bestSellers = products.filter(p => p.isBestSeller)
export const newArrivals = products.filter(p => p.isNew)

export const categories = [
  { id: 'rackets', label: 'Rackets', count: 4, description: 'Pro-grade padel rackets for every level', icon: '🏏' },
  { id: 'balls', label: 'Balls', count: 2, description: 'Tournament-approved match balls', icon: '⚪' },
  { id: 'bags', label: 'Bags', count: 1, description: 'Tour bags with thermal protection', icon: '🎒' },
  { id: 'shoes', label: 'Shoes', count: 2, description: 'Court-specific performance footwear', icon: '👟' },
  { id: 'grips', label: 'Grips', count: 1, description: 'Pro overgrips for any condition', icon: '🎯' },
  { id: 'apparel', label: 'Apparel', count: 1, description: 'Performance padel clothing', icon: '👕' },
  { id: 'accessories', label: 'Accessories', count: 1, description: 'Wristbands, eyewear & more', icon: '🎽' },
]

export const brands = ['All Brands', 'Head', 'Bullpadel', 'Nox', 'Adidas', 'Wilson', 'NEXOR']

export const reviews: Review[] = [
  {
    id: 'r1',
    author: 'Carlos M.',
    rating: 5,
    title: 'Best padel store I\'ve found online',
    body: 'Ordered the Bullpadel Vertex and it arrived in perfect condition next day. The product descriptions are accurate and the quality is exactly as expected. NEXOR Padel is my go-to shop from now on.',
    date: 'March 2025',
    verified: true,
    product: 'Bullpadel Vertex 04 Pro',
  },
  {
    id: 'r2',
    author: 'Ana R.',
    rating: 5,
    title: 'Premium shopping experience',
    body: 'The website is beautiful and easy to use. Found exactly what I needed with great filters. The Nox ML10 I bought is incredible — my coach noticed the improvement immediately. Highly recommend!',
    date: 'April 2025',
    verified: true,
    product: 'Nox ML10 Pro Cup Black',
  },
  {
    id: 'r3',
    author: 'David L.',
    rating: 5,
    title: 'Legit premium gear at great prices',
    body: 'Tried several stores before finding NEXOR. The customer support is fantastic — they helped me choose the right racket for my level. The Adidas Metalbone I got is absolutely incredible.',
    date: 'April 2025',
    verified: true,
    product: 'Adidas Metalbone HT 3.3',
  },
  {
    id: 'r4',
    author: 'Sofia B.',
    rating: 5,
    title: 'Fast shipping, perfect quality',
    body: 'Order arrived within 24 hours. Everything was packaged beautifully. The Head Alpha Pro racket is perfect for my intermediate level — exactly what the description said. Will order again.',
    date: 'May 2025',
    verified: true,
    product: 'Head Alpha Pro 2025',
  },
]

export const faqs: FAQ[] = [
  {
    question: 'How do I choose the right padel racket?',
    answer: 'Choosing a racket depends on your level, playing style, and preferences. Beginners should look for round shapes with medium balance for control. Intermediate players can explore teardrop shapes. Advanced/Pro players typically prefer diamond shapes for maximum power. Our team is happy to help you choose — use the chat or contact us directly.',
  },
  {
    question: 'What are your shipping times and costs?',
    answer: 'We offer free shipping on orders over €75 within the EU. Standard delivery takes 2–4 business days. Express (next-day) delivery is available for most countries at an additional cost. All orders are fully tracked and insured.',
  },
  {
    question: 'Can I return or exchange a product?',
    answer: 'Yes. We offer a 30-day hassle-free return policy. Products must be in original, unused condition with all packaging intact. Rackets that have been used cannot be returned unless they are defective. Exchange for a different model is free within the first 14 days.',
  },
  {
    question: 'Are all products authentic and official?',
    answer: 'Absolutely. NEXOR Padel is an authorised official retailer for all brands we carry. Every product is 100% authentic, comes with the original manufacturer warranty, and is sourced directly from official brand distributors.',
  },
  {
    question: 'Do you offer racket customization or stringing?',
    answer: 'Currently we don\'t offer physical customization services, but we carry a full range of grips, overgrips and accessories to help you personalise your gear. We are working on adding a custom grip service — sign up to our newsletter to be notified.',
  },
  {
    question: 'What payment methods do you accept?',
    answer: 'We accept all major credit and debit cards (Visa, Mastercard, Amex), PayPal, Apple Pay, Google Pay, and bank transfers. All payments are processed through secure, encrypted payment gateways.',
  },
]
