import type { Product, Review, FAQ } from './types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'bullpadel-vertex-04',
    name: 'Vertex 04 Pro',
    brand: 'Bullpadel',
    category: 'rackets',
    price: 1499,
    salePrice: 1199,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    description: 'מחבט ה-Vertex 04 Pro מיועד לשחקנים התקפיים שדורשים עוצמה ושליטה מושלמת בכל מכה.',
    longDescription: 'בנוי עם מסגרת סיבי פחמן חדשנית וליבת EVA Soft פרימיום, מחבט ה-Vertex 04 Pro מספק עוצמת מכה פיצוצית תוך שמירה על שליטה יוצאת דופן. הצורה הדיאמנטית ממקסמת את נקודת המגע עבור שחקנים מתקדמים השואפים לשלוט מקו הבסיס.',
    features: [
      'מסגרת סיבי פחמן High Modulus',
      'ליבת EVA Soft לשליטה עליונה',
      'צורת יהלום למירב העוצמה',
      'מערכת נגד רטט מתקדמת',
      'גריפ פרימיום כלול',
    ],
    playerLevel: 'advanced',
    weight: '355–375 גרם',
    balance: 'איזון גבוה (התקפי)',
    shape: 'יהלום',
    material: 'סיבי פחמן + פיברגלס',
    image: { gradient: 'from-[#0a0a0a] via-[#141414] to-[#0d0d0d]', accent: '#c9a55a' },
    rating: 4.9,
    reviewCount: 142,
    inStock: true,
    stockCount: 8,
  },
  {
    id: '2',
    slug: 'nox-ml10-pro-cup',
    name: 'ML10 Pro Cup Black',
    brand: 'Nox',
    category: 'rackets',
    price: 1799,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    description: 'מחבט החתימה של מיגל למפרטי. בקרה מקסימלית פוגשת דיוק אקסטרים לשחקנות עלית.',
    longDescription: 'המחבט ה-ML10 Pro Cup Black תוכנן בשיתוף עם שחקן מקצוען מיגל למפרטי ומהווה את ברירת המחדל של האלופים. הצורה הגלילית ובניית סיבי הפחמן הרב-שכבתית מספקים את השילוב המושלם של שליטה ודיוק שדורשים מקצוענים.',
    features: [
      'בנייה של 100% סיבי פחמן',
      'טכנולוגיית SMART CROWN',
      'צורה עגולה לשליטה עליונה',
      'שכבות כפולות של סיבי פחמן',
      'מערכת Aluminum Power',
    ],
    playerLevel: 'professional',
    weight: '360–380 גרם',
    balance: 'איזון נמוך-בינוני (שליטה)',
    shape: 'עגול',
    material: '100% סיבי פחמן',
    image: { gradient: 'from-[#080808] via-[#0e160a] to-[#050505]', accent: '#2d7556' },
    rating: 4.8,
    reviewCount: 98,
    inStock: true,
    stockCount: 5,
  },
  {
    id: '3',
    slug: 'head-alpha-pro',
    name: 'Alpha Pro 2025',
    brand: 'Head',
    category: 'rackets',
    price: 899,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    description: 'המחבט המושלם לשחקן הבינוני המוכן לקחת את משחקו לשלב הבא.',
    longDescription: 'ה-Head Alpha Pro 2025 גשר מושלם בין רמת מתחיל לרמת מתקדם. הצורה הטיפה מספקת נקודת מגע נדיבה בעוד שהבנייה משיבי פחמן ופיברגלס מציעה יחס עוצמה-למשקל מעולה.',
    features: [
      'בנייה משולבת פחמן + פיברגלס',
      'צורת טיפה לרב-תכליתיות',
      'איזון בינוני למשחק כולל',
      'ליבת Comfort Foam',
      'מגן קצה מוגן',
    ],
    playerLevel: 'intermediate',
    weight: '360–375 גרם',
    balance: 'איזון בינוני (כולל)',
    shape: 'טיפה',
    material: 'סיבי פחמן + פיברגלס',
    image: { gradient: 'from-[#0a0a12] via-[#0f0f1a] to-[#080810]', accent: '#6366f1' },
    rating: 4.7,
    reviewCount: 203,
    inStock: true,
    stockCount: 15,
  },
  {
    id: '4',
    slug: 'adidas-metalbone-ht',
    name: 'Metalbone HT 3.3',
    brand: 'Adidas',
    category: 'rackets',
    price: 2399,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    description: 'פסגת הנדסת הפאדל של Adidas. עוצמה קיצונית, שליטה קיצונית, אפס פשרות.',
    longDescription: 'ה-Adidas Metalbone HT 3.3 הוא נשק הבחירה של שחקנים מקצוענים המחפשים ביצועים מקסימליים. טכנולוגיית DUAL EXOSKELETON שלו יוצרת מסגרת קשיחה במיוחד שמעבירה אנרגיה מקסימלית בכל מכה.',
    features: [
      'טכנולוגיית DUAL EXOSKELETON',
      'בנייה METALBONE למסגרת',
      'טקסטורת פני שטח SPINTECH',
      'ליבת EVA-HYBRIDFOAM',
      'צורת יהלום אקסטרים',
    ],
    playerLevel: 'professional',
    weight: '365–380 גרם',
    balance: 'איזון גבוה מאוד (עוצמה)',
    shape: 'יהלום',
    material: 'סיבי פחמן + סגסוגת אלומיניום',
    image: { gradient: 'from-[#0a0808] via-[#141010] to-[#080808]', accent: '#ef4444' },
    rating: 4.9,
    reviewCount: 76,
    inStock: true,
    stockCount: 3,
  },
  {
    id: '5',
    slug: 'head-padel-balls-pro',
    name: 'Pro Padel Balls (4 כדורים)',
    brand: 'Head',
    category: 'balls',
    price: 62,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    description: 'כדורי פאדל מאושרים על ידי ITF ו-FIP לתחרויות מקצועיות. עמידות וניתור עקביים.',
    longDescription: 'כדורי Head Pro משמשים ברמות התחרות הגבוהות ביותר בעולם. כל כדור מתוכנן בדיוק ללחץ עקבי, גובה ניתור אופטימלי ועמידות מורחבת על כל משטח מגרש.',
    features: [
      'מאושרים על ידי FIP ו-ITF',
      'לחץ פנימי עקבי',
      'פלוס פרימיום לעמידות',
      'גובה ניתור אופטימלי',
      'אריזה של 4 כדורים',
    ],
    image: { gradient: 'from-[#0a0a08] via-[#141408] to-[#0d0d07]', accent: '#eab308' },
    rating: 4.8,
    reviewCount: 512,
    inStock: true,
  },
  {
    id: '6',
    slug: 'bullpadel-balls-official',
    name: 'Official Match Balls (3 כדורים)',
    brand: 'Bullpadel',
    category: 'balls',
    price: 59,
    salePrice: 49,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    description: 'כדורי תחרות ברמה מקצועית עם שמירת לחץ עליונה למשחק תחרותי.',
    longDescription: 'כדורי Bullpadel Official מיועדים למשחק תחרותי עם שמירת לחץ עליונה וניתור עקבי. בנייה בפלוס איכותית מספקת תגובת ספין מעולה ועמידות.',
    features: [
      'שמירת לחץ גבוהה',
      'פלוס באיכות פרימיום',
      'תגובת ספין מעולה',
      'אריזה של 3 כדורים',
      'כל משטחי מגרש',
    ],
    image: { gradient: 'from-[#0a0c08] via-[#12160a] to-[#0a0c08]', accent: '#84cc16' },
    rating: 4.6,
    reviewCount: 287,
    inStock: true,
  },
  {
    id: '7',
    slug: 'head-xtreme-soft-grip',
    name: 'Xtreme Soft Grip (3 יחידות)',
    brand: 'Head',
    category: 'grips',
    price: 69,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    description: 'אוברגריפ רך במיוחד לנוחות מקסימלית וספיגת לחות מעולה במהלך משחק אינטנסיבי.',
    longDescription: 'גריפ Head Xtreme Soft מספק נוחות יוצאת דופן עם בנייתו הדקה במיוחד וטכנולוגיית ספיגת הלחות המתקדמת. מושלם לשחקנים שמזיעים הרבה או מעדיפים תחושה רכה יותר.',
    features: [
      'טקסטורה רכה במיוחד',
      'ספיגת לחות עליונה',
      'פרופיל דק של 0.6 מ"מ',
      'פני שטח נגד החלקה',
      'אריזה של 3 גריפים',
    ],
    color: 'לבן / שחור / לימה',
    image: { gradient: 'from-[#080a0a] via-[#0f1212] to-[#080a0a]', accent: '#22d3ee' },
    rating: 4.7,
    reviewCount: 435,
    inStock: true,
  },
  {
    id: '8',
    slug: 'bullpadel-tour-bag',
    name: 'Tour Pro Bag 2025',
    brand: 'Bullpadel',
    category: 'bags',
    price: 799,
    salePrice: 599,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    description: 'תיק טורניר מקצועי עם כיס תרמי ל-3 מחבטים וארגון ציוד מלא.',
    longDescription: 'תיק ה-Bullpadel Tour Pro הוא הפתרון המלא לשחקן הרציני. עם כיס תרמי ייעודי המגן על עד 3 מחבטים מטמפרטורות קיצוניות, תאים מרובים לנעליים, ביגוד ואביזרים, ורצועות כתף ארגונומיות, התיק הזה בנוי לשחקן שמוציא הכל על המגרש.',
    features: [
      'כיס תרמי ל-3 מחבטים',
      'תא נעליים נפרד',
      'כיסים מרובים לאביזרים',
      'חומר עמיד למים',
      'רצועות ארגונומיות ממולאות',
    ],
    color: 'שחור / לימה',
    image: { gradient: 'from-[#0a0a0a] via-[#121512] to-[#080a08]', accent: '#c9a55a' },
    rating: 4.8,
    reviewCount: 167,
    inStock: true,
    stockCount: 12,
  },
  {
    id: '9',
    slug: 'adidas-adipower-ctrl-3',
    name: 'Adipower CTRL 3',
    brand: 'Adidas',
    category: 'shoes',
    price: 699,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    description: 'נעלי פאדל עלית מהונדסות לתנועות לרוחב פיצוציות ואחיזה מעולה בכל המגרש.',
    longDescription: 'ה-Adidas Adipower CTRL 3 משלב טכנולוגיית אחיזה מתקדמת עם תמיכה לרוחב עליונה לדרישות הפאדל המודרני. דפוס הסוליה ה-Herringbone מספק אחיזה אופטימלית על כל משטחי מגרש.',
    features: [
      'סוליה Herringbone לאחיזה מיטבית',
      'טכנולוגיית ריפוד BOOST',
      'חרטום מחוזק',
      'גפה נושמת',
      'מערכת תמיכה לרוחב',
    ],
    size: 'EU 38–48',
    color: 'שחור / לבן / לימה',
    image: { gradient: 'from-[#080810] via-[#0f0f1a] to-[#080810]', accent: '#818cf8' },
    rating: 4.7,
    reviewCount: 93,
    inStock: true,
  },
  {
    id: '10',
    slug: 'nox-shoes-nerbo-10',
    name: 'Nerbo 10 Performance',
    brand: 'Nox',
    category: 'shoes',
    price: 549,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    description: 'נעלי ביצועים קלות עם אחיזה יוצאת דופן לתנועות פאדל מהירות.',
    longDescription: 'נעלי Nox Nerbo 10 מיועדות לשחקנים המעניקים עדיפות למהירות וזריזות. הבנייה הקלה ודפוס הסוליה הכיווני מספקים תחושת מגרש מעולה ותנועה מהירה לכל כיוון.',
    features: [
      'בנייה קלה (פחות מ-400 גרם)',
      'דפוס סוליה כיווני',
      'צווארון קרסול ממולא',
      'גפה עם ייבוש מהיר',
      'חיזוקי TPU עמידים',
    ],
    size: 'EU 38–47',
    color: 'שחור / ירוק לימה',
    image: { gradient: 'from-[#080a08] via-[#0f1a0f] to-[#080a08]', accent: '#2d7556' },
    rating: 4.6,
    reviewCount: 124,
    inStock: true,
  },
  {
    id: '11',
    slug: 'babolat-technical-tee',
    name: 'Technical Tee Pro',
    brand: 'Babolat',
    category: 'apparel',
    price: 249,
    isNew: true,
    isBestSeller: false,
    isFeatured: false,
    description: 'חולצת פאדל טכנית של Babolat עם טכנולוגיית ניהול לחות מתקדמת.',
    longDescription: 'חולצת הביצועים של Babolat מהונדסת לאימוני פאדל בעצימות גבוהה. הבד המתקדם עם הטחת לחות שומר עליך קריר ויבש לאורך כל המשחק. עיצוב פרו בסגנון השחקנים המקצועיים.',
    features: [
      'טכנולוגיית ניהול לחות מתקדמת',
      'חיתוך אתלטי לחופש מלא בתנועה',
      'טיפול נגד ריח',
      'הגנת UPF 40+ מהשמש',
      'עיצוב Babolat Pro',
    ],
    size: 'XS–XXL',
    color: 'שחור / כחול נייבי',
    image: { gradient: 'from-[#050505] via-[#080e1a] to-[#050505]', accent: '#c9a55a' },
    rating: 4.8,
    reviewCount: 56,
    inStock: true,
  },
  {
    id: '12',
    slug: 'wilson-padel-wristband',
    name: 'סט צמידי זיעה מקצועיים',
    brand: 'Wilson',
    category: 'accessories',
    price: 59,
    isNew: false,
    isBestSeller: false,
    isFeatured: false,
    description: 'צמידי זיעה פרימיום מכותנה לספיגת הזעה עליונה במהלך משחקי פאדל אינטנסיביים.',
    longDescription: 'צמידי Wilson Pro עשויים מכותנה-טרי עם שילוב איכותי לספיגת זיעה מקסימלית. העיצוב המגומי מבטיח שיישארו במקומם גם במחטפים הכי אינטנסיביים.',
    features: [
      'שילוב כותנה-טרי',
      'ספיגת זיעה גבוהה',
      'התאמה למידת כף יד',
      'ניתן לכביסה במכונה',
      'אריזה של 2 צמידים',
    ],
    color: 'לבן / שחור / לימה',
    image: { gradient: 'from-[#0a0808] via-[#141010] to-[#0a0808]', accent: '#f87171' },
    rating: 4.5,
    reviewCount: 312,
    inStock: true,
  },
]

export const featuredProducts = products.filter(p => p.isFeatured)
export const bestSellers = products.filter(p => p.isBestSeller)
export const newArrivals = products.filter(p => p.isNew)

export const categories = [
  { id: 'rackets', label: 'מחבטים', count: 4, description: 'מחבטי פאדל ברמת מקצוענים לכל רמה', icon: '🎾' },
  { id: 'balls', label: 'כדורים', count: 2, description: 'כדורים מאושרים לתחרויות', icon: '⚪' },
  { id: 'bags', label: 'תיקים', count: 1, description: 'תיקי טורניר עם הגנה תרמית', icon: '🎒' },
  { id: 'shoes', label: 'נעליים', count: 2, description: 'נעלי ביצועים לפאדל', icon: '👟' },
  { id: 'grips', label: 'גריפים', count: 1, description: 'אוברגריפ לכל תנאי', icon: '🎯' },
  { id: 'apparel', label: 'ביגוד', count: 1, description: 'ביגוד פאדל מקצועי', icon: '👕' },
  { id: 'accessories', label: 'אביזרים', count: 1, description: 'צמידים, משקפיים ועוד', icon: '🎽' },
]

export const brands = [
  'כל המותגים',
  'Head',
  'Bullpadel',
  'Nox',
  'Adidas',
  'Wilson',
  'Babolat',
  'StarVie',
  'Siux',
  'Drop Shot',
  'Asics',
  'Mizuno',
  'Joma',
  'Munich',
  'K-Swiss',
]

export const playerLevelLabels: Record<string, string> = {
  beginner: 'מתחיל',
  intermediate: 'בינוני',
  advanced: 'מתקדם',
  professional: 'מקצועי',
}

export const reviews: Review[] = [
  {
    id: 'r1',
    author: 'קרלוס מ.',
    rating: 5,
    title: 'חנות הפאדל הכי טובה בישראל',
    body: 'הזמנתי את Bullpadel Vertex ויום אחרי ההזמנה הוא כבר אצלי. האריזה יפה, הציוד מקורי ומושלם. NEXOR Padel היא ברמה אחרת לגמרי — שירות, מהירות ואיכות.',
    date: 'מרץ 2025',
    verified: true,
    product: 'Bullpadel Vertex 04 Pro',
  },
  {
    id: 'r2',
    author: 'אנה ר.',
    rating: 5,
    title: 'חווית קנייה פרימיום',
    body: 'האתר יפה ונוח לשימוש. מצאתי בדיוק מה שחיפשתי עם פילטרים מעולים. המחבט Nox ML10 שקניתי מדהים — המאמן שלי שם לב לשיפור מיד. ממליצה בחום!',
    date: 'אפריל 2025',
    verified: true,
    product: 'Nox ML10 Pro Cup Black',
  },
  {
    id: 'r3',
    author: 'דוד ל.',
    rating: 5,
    title: 'ציוד אמיתי במחירים שפויים',
    body: 'ניסיתי כמה חנויות לפני שמצאתי את NEXOR. התמיכה לקוחות יוצאת מהכלל — עזרו לי לבחור מחבט שמתאים לרמה שלי. ה-Adidas Metalbone שקיבלתי פשוט מושלם.',
    date: 'אפריל 2025',
    verified: true,
    product: 'Adidas Metalbone HT 3.3',
  },
  {
    id: 'r4',
    author: 'סופיה ב.',
    rating: 5,
    title: 'משלוח מהיר, איכות מושלמת',
    body: 'ההזמנה הגיעה תוך 24 שעות. הכל היה ארוז בצורה יפה ומקצועית. מחבט Alpha Pro מושלם לרמה הבינונית שלי — בדיוק כמו שהתיאור אמר. אזמין שוב.',
    date: 'מאי 2025',
    verified: true,
    product: 'Head Alpha Pro 2025',
  },
]

export const faqs: FAQ[] = [
  {
    question: 'כיצד אבחר את המחבט הנכון?',
    answer: 'בחירת מחבט תלויה ברמת המשחק שלך, בסגנון ובהעדפות אישיות. מתחילים צריכים לחפש צורת עיגול עם איזון בינוני לשליטה. שחקנים בינוניים יכולים לנסות צורת טיפה. שחקנים מתקדמים ומקצועיים בדרך כלל מעדיפים צורת יהלום לעוצמה מקסימלית. הצוות שלנו שמח לעזור לך לבחור — כתוב לנו בוואטסאפ.',
  },
  {
    question: 'מה זמני ומחירי המשלוח?',
    answer: 'אנחנו מציעים משלוח חינם על הזמנות מעל ₪280 בכל רחבי ישראל. משלוח סטנדרטי לוקח 2–3 ימי עסקים. משלוח אקספרס (ליום המחרת) זמין בעלות נוספת. כל ההזמנות כוללות מעקב מלא.',
  },
  {
    question: 'האם ניתן להחזיר או להחליף מוצר?',
    answer: 'כן. אנחנו מציעים מדיניות החזרה נוחה של 30 יום. המוצרים חייבים להיות במצב מקורי ובלתי בשימוש עם כל האריזה שלמה. מחבטים שנעשה בהם שימוש לא ניתן להחזרה אלא אם כן יש פגם. החלפה לדגם שונה חינמית בתוך 14 הימים הראשונים.',
  },
  {
    question: 'האם כל המוצרים מקוריים ורשמיים?',
    answer: 'בהחלט. NEXOR Padel היא ספקית מורשית רשמית לכל המותגים שאנחנו נושאים. כל מוצר הוא 100% אותנטי, מגיע עם אחריות יצרן מקורית, ומסופק ישירות מהמפיצים הרשמיים.',
  },
  {
    question: 'האם אתם מציעים התאמת ידיות?',
    answer: 'כרגע איננו מציעים שירות התאמה פיזי, אך אנחנו נושאים מגוון רחב של גריפים ואוברגריפים שיעזרו לך להתאים אישית את הציוד שלך. אנחנו עובדים על שירות גריפ מותאם — הירשם לניוזלטר שלנו כדי להיות הראשון לדעת.',
  },
  {
    question: 'אילו אמצעי תשלום מתקבלים?',
    answer: 'אנחנו מקבלים את כל כרטיסי האשראי והחיוב הגדולים (ויזה, מאסטרקארד, אמקס), PayPal, Apple Pay ו-Google Pay. כל התשלומים מעובדים דרך שערי תשלום מוצפנים ומאובטחים.',
  },
]
